# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test123' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test123
pod "PGFramework"
  target 'Test123Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test123UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
